using CSharpVitamins;
using FluentValidation;
using MediatR;
using Raytha.Application.Common.Interfaces;
using Raytha.Application.Common.Models;
using Raytha.Application.Common.Utils;
using Raytha.Domain.Entities;
using Raytha.Domain.Events;
using Raytha.Domain.ValueObjects;

namespace Raytha.Application.Users.Commands;

public class CreateUser
{
    public record Command : LoggableRequest<CommandResponseDto<ShortGuid>>
    {
        public string FirstName { get; init; } = null!;
        public string LastName { get; init; } = null!;
        public string EmailAddress { get; init; } = null!;
        public IEnumerable<ShortGuid> UserGroups { get; init; } = new List<ShortGuid>();
        public bool SendEmail { get; init; }
    }

    public class Validator : AbstractValidator<Command>
    {
        public Validator(IRaythaDbContext db)
        {
            RuleFor(x => x.FirstName).NotEmpty();
            RuleFor(x => x.LastName).NotEmpty();
            RuleFor(x => x.EmailAddress).NotEmpty().EmailAddress();
            RuleFor(x => x).Custom((request, context) =>
            {
                var entity = db.Users
                    .FirstOrDefault(p => p.EmailAddress.ToLower() == request.EmailAddress.ToLower());

                if (entity != null)
                {
                    context.AddFailure("EmailAddress", "Another user with this email address already exists.");
                    return;
                }
            });
        }
    }

    public class Handler : IRequestHandler<Command, CommandResponseDto<ShortGuid>>
    {
        private readonly IRaythaDbContext _db;
        public Handler(IRaythaDbContext db)
        {
            _db = db;
        }
        public async Task<CommandResponseDto<ShortGuid>> Handle(Command request, CancellationToken cancellationToken)
        {
            var autoGeneratedPassword = PasswordUtility.RandomPassword(12);

            var defaultToEmailAndPasswordScheme = _db.AuthenticationSchemes.First(p => p.DeveloperName == AuthenticationSchemeType.EmailAndPassword.DeveloperName);
            var salt = PasswordUtility.RandomSalt();
            var newUserId = Guid.NewGuid();
            var entity = new User
            {
                Id = newUserId,
                FirstName = request.FirstName,
                LastName = request.LastName,
                EmailAddress = request.EmailAddress,
                IsActive = true,
                IsAdmin = false,
                Salt = salt,
                PasswordHash = PasswordUtility.Hash(autoGeneratedPassword, salt),
                SsoId = (ShortGuid)newUserId,
                AuthenticationSchemeId = defaultToEmailAndPasswordScheme.Id
            };

            entity.UserGroups = new List<UserGroup>();
            if (request.UserGroups != null)
            {
                foreach (var userGroupToAddId in request.UserGroups)
                {
                    var userGroupToAdd = _db.UserGroups.First(p => p.Id == userGroupToAddId.Guid);
                    entity.UserGroups.Add(userGroupToAdd);
                }
            }


            entity.AddDomainEvent(new UserCreatedEvent(entity, request.SendEmail, autoGeneratedPassword));

            _db.Users.Add(entity);
            
            await _db.SaveChangesAsync(cancellationToken);
            return new CommandResponseDto<ShortGuid>(entity.Id);
        }
    }
}
