<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>7e3df06b-f996-4ba5-8631-62cd855692f8</UserSecretsId>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <Nullable>enable</Nullable>
    <RootNamespace>Raytha.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="Fluid.Core" />
    <PackageReference Include="Fluid.ViewEngine" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
  <ItemGroup Label="Observability">
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="Sentry.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Grafana.Loki" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Raytha.Application\Raytha.Application.csproj" />
    <ProjectReference Include="..\Raytha.Infrastructure\Raytha.Infrastructure.csproj" />
  </ItemGroup>
</Project>
