CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AuditLogs" (
    "Id" uuid NOT NULL,
    "EntityId" uuid,
    "Category" text NOT NULL,
    "Request" text NOT NULL,
    "UserEmail" text NOT NULL,
    "IpAddress" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "BackgroundTasks" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Args" text,
    "ErrorMessage" text,
    "Status" text NOT NULL,
    "StatusInfo" text,
    "PercentComplete" integer NOT NULL,
    "NumberOfRetries" integer NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CompletionTime" timestamp with time zone,
    "TaskStep" integer NOT NULL,
    CONSTRAINT "PK_BackgroundTasks" PRIMARY KEY ("Id")
);

CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "JwtLogins" (
    "Id" uuid NOT NULL,
    "Jti" text,
    "CreationTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_JwtLogins" PRIMARY KEY ("Id")
);

CREATE TABLE "OrganizationSettings" (
    "Id" uuid NOT NULL,
    "OrganizationName" text,
    "WebsiteUrl" text,
    "TimeZone" text,
    "DateFormat" text,
    "SmtpOverrideSystem" boolean NOT NULL,
    "SmtpHost" text,
    "SmtpPort" integer,
    "SmtpUsername" text,
    "SmtpPassword" text,
    "SmtpDefaultFromAddress" text,
    "SmtpDefaultFromName" text,
    "HomePageId" uuid,
    "HomePageType" text NOT NULL,
    "ActiveThemeId" uuid NOT NULL,
    CONSTRAINT "PK_OrganizationSettings" PRIMARY KEY ("Id")
);

CREATE TABLE "Routes" (
    "Id" uuid NOT NULL,
    "Path" text NOT NULL,
    "ContentItemId" uuid NOT NULL,
    "ViewId" uuid NOT NULL,
    CONSTRAINT "PK_Routes" PRIMARY KEY ("Id")
);

CREATE TABLE "ApiKeys" (
    "Id" uuid NOT NULL,
    "ApiKeyHash" bytea NOT NULL,
    "UserId" uuid NOT NULL,
    "CreatorUserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "AuthenticationSchemes" (
    "Id" uuid NOT NULL,
    "IsBuiltInAuth" boolean NOT NULL,
    "IsEnabledForUsers" boolean NOT NULL,
    "IsEnabledForAdmins" boolean NOT NULL,
    "AuthenticationSchemeType" text,
    "Label" text,
    "DeveloperName" text,
    "MagicLinkExpiresInSeconds" integer NOT NULL,
    "SamlCertificate" text,
    "SamlIdpEntityId" text,
    "JwtSecretKey" text,
    "JwtUseHighSecurity" boolean NOT NULL,
    "SignInUrl" text,
    "LoginButtonText" text,
    "SignOutUrl" text,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_AuthenticationSchemes" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "LastLoggedInTime" timestamp with time zone,
    "Salt" bytea NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "SsoId" text,
    "AuthenticationSchemeId" uuid,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "EmailAddress" text NOT NULL,
    "IsEmailAddressConfirmed" boolean NOT NULL,
    "_RecentlyAccessedViews" text,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_AuthenticationSchemes_AuthenticationSchemeId" FOREIGN KEY ("AuthenticationSchemeId") REFERENCES "AuthenticationSchemes" ("Id"),
    CONSTRAINT "FK_Users_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Users_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "ContentTypes" (
    "Id" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "LabelPlural" text,
    "LabelSingular" text,
    "DeveloperName" text,
    "Description" text,
    "DefaultRouteTemplate" text,
    "PrimaryFieldId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    "DeleterUserId" uuid,
    "DeletionTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ContentTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContentTypes_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_ContentTypes_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "EmailTemplates" (
    "Id" uuid NOT NULL,
    "Subject" text,
    "DeveloperName" text,
    "Cc" text,
    "Bcc" text,
    "Content" text,
    "IsBuiltInTemplate" boolean NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_EmailTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailTemplates_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_EmailTemplates_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "MediaItems" (
    "Id" uuid NOT NULL,
    "Length" bigint NOT NULL,
    "FileName" text NOT NULL,
    "ContentType" text NOT NULL,
    "FileStorageProvider" text NOT NULL,
    "ObjectKey" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_MediaItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaItems_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_MediaItems_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "NavigationMenus" (
    "Id" uuid NOT NULL,
    "Label" text NOT NULL,
    "DeveloperName" text NOT NULL,
    "IsMainMenu" boolean NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_NavigationMenus" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NavigationMenus_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_NavigationMenus_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "OneTimePasswords" (
    "Id" bytea NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_OneTimePasswords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OneTimePasswords_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RaythaFunctions" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "DeveloperName" text NOT NULL,
    "TriggerType" text NOT NULL,
    "Code" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_RaythaFunctions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RaythaFunctions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_RaythaFunctions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Label" text NOT NULL,
    "DeveloperName" text NOT NULL,
    "SystemPermissions" integer NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Roles_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Roles_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "Themes" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "DeveloperName" text NOT NULL,
    "Description" text NOT NULL,
    "IsExportable" boolean NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_Themes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Themes_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Themes_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "UserGroups" (
    "Id" uuid NOT NULL,
    "Label" text NOT NULL,
    "DeveloperName" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_UserGroups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserGroups_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_UserGroups_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "VerificationCodes" (
    "Id" uuid NOT NULL,
    "Code" uuid NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Completed" boolean NOT NULL,
    "EmailAddress" text,
    "VerificationCodeType" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_VerificationCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VerificationCodes_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_VerificationCodes_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "ContentItems" (
    "Id" uuid NOT NULL,
    "IsPublished" boolean NOT NULL,
    "IsDraft" boolean NOT NULL,
    "_DraftContent" text,
    "_PublishedContent" jsonb,
    "ContentTypeId" uuid NOT NULL,
    "RouteId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_ContentItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContentItems_ContentTypes_ContentTypeId" FOREIGN KEY ("ContentTypeId") REFERENCES "ContentTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContentItems_Routes_RouteId" FOREIGN KEY ("RouteId") REFERENCES "Routes" ("Id"),
    CONSTRAINT "FK_ContentItems_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_ContentItems_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "ContentTypeFields" (
    "Id" uuid NOT NULL,
    "Label" text,
    "DeveloperName" text,
    "Description" text,
    "FieldOrder" integer NOT NULL,
    "IsRequired" boolean NOT NULL,
    "RelatedContentTypeId" uuid,
    "ContentTypeId" uuid NOT NULL,
    "FieldType" text NOT NULL,
    "_Choices" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    "DeleterUserId" uuid,
    "DeletionTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ContentTypeFields" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContentTypeFields_ContentTypes_ContentTypeId" FOREIGN KEY ("ContentTypeId") REFERENCES "ContentTypes" ("Id"),
    CONSTRAINT "FK_ContentTypeFields_ContentTypes_RelatedContentTypeId" FOREIGN KEY ("RelatedContentTypeId") REFERENCES "ContentTypes" ("Id"),
    CONSTRAINT "FK_ContentTypeFields_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_ContentTypeFields_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "DeletedContentItems" (
    "Id" uuid NOT NULL,
    "_PublishedContent" text,
    "PrimaryField" text,
    "ContentTypeId" uuid NOT NULL,
    "OriginalContentItemId" uuid NOT NULL,
    "RoutePath" text NOT NULL,
    "WebTemplateIdsJson" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_DeletedContentItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeletedContentItems_ContentTypes_ContentTypeId" FOREIGN KEY ("ContentTypeId") REFERENCES "ContentTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DeletedContentItems_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_DeletedContentItems_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "Views" (
    "Id" uuid NOT NULL,
    "Label" text,
    "DeveloperName" text,
    "Description" text,
    "ContentTypeId" uuid NOT NULL,
    "RouteId" uuid NOT NULL,
    "IsPublished" boolean NOT NULL,
    "DefaultNumberOfItemsPerPage" integer NOT NULL,
    "MaxNumberOfItemsPerPage" integer NOT NULL,
    "IgnoreClientFilterAndSortQueryParams" boolean NOT NULL,
    "_Columns" text,
    "_Filter" text,
    "_Sort" text,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_Views" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Views_ContentTypes_ContentTypeId" FOREIGN KEY ("ContentTypeId") REFERENCES "ContentTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Views_Routes_RouteId" FOREIGN KEY ("RouteId") REFERENCES "Routes" ("Id"),
    CONSTRAINT "FK_Views_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Views_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "EmailTemplateRevisions" (
    "Id" uuid NOT NULL,
    "Subject" text,
    "Content" text,
    "Cc" text,
    "Bcc" text,
    "EmailTemplateId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_EmailTemplateRevisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailTemplateRevisions_EmailTemplates_EmailTemplateId" FOREIGN KEY ("EmailTemplateId") REFERENCES "EmailTemplates" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmailTemplateRevisions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_EmailTemplateRevisions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "NavigationMenuItems" (
    "Id" uuid NOT NULL,
    "Label" text NOT NULL,
    "Url" text NOT NULL,
    "IsDisabled" boolean NOT NULL,
    "OpenInNewTab" boolean NOT NULL,
    "CssClassName" text,
    "Ordinal" integer NOT NULL,
    "ParentNavigationMenuItemId" uuid,
    "NavigationMenuId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_NavigationMenuItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NavigationMenuItems_NavigationMenuItems_ParentNavigationMen~" FOREIGN KEY ("ParentNavigationMenuItemId") REFERENCES "NavigationMenuItems" ("Id"),
    CONSTRAINT "FK_NavigationMenuItems_NavigationMenus_NavigationMenuId" FOREIGN KEY ("NavigationMenuId") REFERENCES "NavigationMenus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NavigationMenuItems_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_NavigationMenuItems_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "NavigationMenuRevisions" (
    "Id" uuid NOT NULL,
    "NavigationMenuItemsJson" text NOT NULL,
    "NavigationMenuId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_NavigationMenuRevisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NavigationMenuRevisions_NavigationMenus_NavigationMenuId" FOREIGN KEY ("NavigationMenuId") REFERENCES "NavigationMenus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_NavigationMenuRevisions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_NavigationMenuRevisions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "RaythaFunctionRevisions" (
    "Id" uuid NOT NULL,
    "Code" text NOT NULL,
    "RaythaFunctionId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_RaythaFunctionRevisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RaythaFunctionRevisions_RaythaFunctions_RaythaFunctionId" FOREIGN KEY ("RaythaFunctionId") REFERENCES "RaythaFunctions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RaythaFunctionRevisions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_RaythaFunctionRevisions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "ContentTypeRolePermission" (
    "Id" uuid NOT NULL,
    "ContentTypeId" uuid NOT NULL,
    "ContentTypePermissions" integer NOT NULL,
    "RoleId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_ContentTypeRolePermission" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContentTypeRolePermission_ContentTypes_ContentTypeId" FOREIGN KEY ("ContentTypeId") REFERENCES "ContentTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContentTypeRolePermission_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContentTypeRolePermission_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_ContentTypeRolePermission_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "RoleUser" (
    "RolesId" uuid NOT NULL,
    "UsersId" uuid NOT NULL,
    CONSTRAINT "PK_RoleUser" PRIMARY KEY ("RolesId", "UsersId"),
    CONSTRAINT "FK_RoleUser_Roles_RolesId" FOREIGN KEY ("RolesId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoleUser_Users_UsersId" FOREIGN KEY ("UsersId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ThemeAccessToMediaItems" (
    "Id" uuid NOT NULL,
    "ThemeId" uuid NOT NULL,
    "MediaItemId" uuid NOT NULL,
    CONSTRAINT "PK_ThemeAccessToMediaItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ThemeAccessToMediaItems_MediaItems_MediaItemId" FOREIGN KEY ("MediaItemId") REFERENCES "MediaItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ThemeAccessToMediaItems_Themes_ThemeId" FOREIGN KEY ("ThemeId") REFERENCES "Themes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WebTemplates" (
    "Id" uuid NOT NULL,
    "ThemeId" uuid NOT NULL,
    "IsBaseLayout" boolean NOT NULL,
    "Label" text,
    "DeveloperName" text,
    "Content" text,
    "IsBuiltInTemplate" boolean NOT NULL,
    "ParentTemplateId" uuid,
    "AllowAccessForNewContentTypes" boolean NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_WebTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WebTemplates_Themes_ThemeId" FOREIGN KEY ("ThemeId") REFERENCES "Themes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WebTemplates_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WebTemplates_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WebTemplates_WebTemplates_ParentTemplateId" FOREIGN KEY ("ParentTemplateId") REFERENCES "WebTemplates" ("Id")
);

CREATE TABLE "UserUserGroup" (
    "UserGroupsId" uuid NOT NULL,
    "UsersId" uuid NOT NULL,
    CONSTRAINT "PK_UserUserGroup" PRIMARY KEY ("UserGroupsId", "UsersId"),
    CONSTRAINT "FK_UserUserGroup_UserGroups_UserGroupsId" FOREIGN KEY ("UserGroupsId") REFERENCES "UserGroups" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserUserGroup_Users_UsersId" FOREIGN KEY ("UsersId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContentItemRevisions" (
    "Id" uuid NOT NULL,
    "_PublishedContent" text,
    "ContentItemId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_ContentItemRevisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContentItemRevisions_ContentItems_ContentItemId" FOREIGN KEY ("ContentItemId") REFERENCES "ContentItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContentItemRevisions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_ContentItemRevisions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "UserView" (
    "FavoriteViewsId" uuid NOT NULL,
    "UserFavoritesId" uuid NOT NULL,
    CONSTRAINT "PK_UserView" PRIMARY KEY ("FavoriteViewsId", "UserFavoritesId"),
    CONSTRAINT "FK_UserView_Users_UserFavoritesId" FOREIGN KEY ("UserFavoritesId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserView_Views_FavoriteViewsId" FOREIGN KEY ("FavoriteViewsId") REFERENCES "Views" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WebTemplateAccessToModelDefinitions" (
    "Id" uuid NOT NULL,
    "WebTemplateId" uuid NOT NULL,
    "ContentTypeId" uuid NOT NULL,
    CONSTRAINT "PK_WebTemplateAccessToModelDefinitions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WebTemplateAccessToModelDefinitions_ContentTypes_ContentTyp~" FOREIGN KEY ("ContentTypeId") REFERENCES "ContentTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WebTemplateAccessToModelDefinitions_WebTemplates_WebTemplat~" FOREIGN KEY ("WebTemplateId") REFERENCES "WebTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WebTemplateContentItemRelations" (
    "Id" uuid NOT NULL,
    "WebTemplateId" uuid NOT NULL,
    "ContentItemId" uuid NOT NULL,
    CONSTRAINT "PK_WebTemplateContentItemRelations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WebTemplateContentItemRelations_ContentItems_ContentItemId" FOREIGN KEY ("ContentItemId") REFERENCES "ContentItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WebTemplateContentItemRelations_WebTemplates_WebTemplateId" FOREIGN KEY ("WebTemplateId") REFERENCES "WebTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WebTemplateRevisions" (
    "Id" uuid NOT NULL,
    "Label" text,
    "Content" text,
    "WebTemplateId" uuid NOT NULL,
    "AllowAccessForNewContentTypes" boolean NOT NULL,
    "EmailTemplateId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_WebTemplateRevisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WebTemplateRevisions_EmailTemplates_EmailTemplateId" FOREIGN KEY ("EmailTemplateId") REFERENCES "EmailTemplates" ("Id"),
    CONSTRAINT "FK_WebTemplateRevisions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WebTemplateRevisions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WebTemplateRevisions_WebTemplates_WebTemplateId" FOREIGN KEY ("WebTemplateId") REFERENCES "WebTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WebTemplateViewRelations" (
    "Id" uuid NOT NULL,
    "WebTemplateId" uuid NOT NULL,
    "ViewId" uuid NOT NULL,
    CONSTRAINT "PK_WebTemplateViewRelations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WebTemplateViewRelations_Views_ViewId" FOREIGN KEY ("ViewId") REFERENCES "Views" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WebTemplateViewRelations_WebTemplates_WebTemplateId" FOREIGN KEY ("WebTemplateId") REFERENCES "WebTemplates" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_ApiKeys_ApiKeyHash" ON "ApiKeys" ("ApiKeyHash");

CREATE INDEX "IX_ApiKeys_CreatorUserId" ON "ApiKeys" ("CreatorUserId");

CREATE INDEX "IX_ApiKeys_UserId" ON "ApiKeys" ("UserId");

CREATE INDEX "IX_AuditLogs_Category" ON "AuditLogs" ("Category");

CREATE INDEX "IX_AuditLogs_CreationTime" ON "AuditLogs" ("CreationTime");

CREATE INDEX "IX_AuditLogs_EntityId" ON "AuditLogs" ("EntityId");

CREATE INDEX "IX_AuthenticationSchemes_CreatorUserId" ON "AuthenticationSchemes" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_AuthenticationSchemes_DeveloperName" ON "AuthenticationSchemes" ("DeveloperName");

CREATE INDEX "IX_AuthenticationSchemes_LastModifierUserId" ON "AuthenticationSchemes" ("LastModifierUserId");

CREATE INDEX "IX_ContentItemRevisions_ContentItemId" ON "ContentItemRevisions" ("ContentItemId");

CREATE INDEX "IX_ContentItemRevisions_CreatorUserId" ON "ContentItemRevisions" ("CreatorUserId");

CREATE INDEX "IX_ContentItemRevisions_LastModifierUserId" ON "ContentItemRevisions" ("LastModifierUserId");

CREATE INDEX "IX_ContentItems_ContentTypeId" ON "ContentItems" ("ContentTypeId");

CREATE INDEX "IX_ContentItems_CreatorUserId" ON "ContentItems" ("CreatorUserId");

CREATE INDEX "IX_ContentItems_LastModifierUserId" ON "ContentItems" ("LastModifierUserId");

CREATE UNIQUE INDEX "IX_ContentItems_RouteId" ON "ContentItems" ("RouteId");

CREATE INDEX "IX_ContentTypeFields_ContentTypeId" ON "ContentTypeFields" ("ContentTypeId");

CREATE INDEX "IX_ContentTypeFields_CreatorUserId" ON "ContentTypeFields" ("CreatorUserId");

CREATE INDEX "IX_ContentTypeFields_LastModifierUserId" ON "ContentTypeFields" ("LastModifierUserId");

CREATE INDEX "IX_ContentTypeFields_RelatedContentTypeId" ON "ContentTypeFields" ("RelatedContentTypeId");

CREATE INDEX "IX_ContentTypeRolePermission_ContentTypeId" ON "ContentTypeRolePermission" ("ContentTypeId");

CREATE INDEX "IX_ContentTypeRolePermission_CreatorUserId" ON "ContentTypeRolePermission" ("CreatorUserId");

CREATE INDEX "IX_ContentTypeRolePermission_LastModifierUserId" ON "ContentTypeRolePermission" ("LastModifierUserId");

CREATE INDEX "IX_ContentTypeRolePermission_RoleId" ON "ContentTypeRolePermission" ("RoleId");

CREATE INDEX "IX_ContentTypes_CreatorUserId" ON "ContentTypes" ("CreatorUserId");

CREATE INDEX "IX_ContentTypes_LastModifierUserId" ON "ContentTypes" ("LastModifierUserId");

CREATE INDEX "IX_DeletedContentItems_ContentTypeId" ON "DeletedContentItems" ("ContentTypeId");

CREATE INDEX "IX_DeletedContentItems_CreatorUserId" ON "DeletedContentItems" ("CreatorUserId");

CREATE INDEX "IX_DeletedContentItems_LastModifierUserId" ON "DeletedContentItems" ("LastModifierUserId");

CREATE INDEX "IX_EmailTemplateRevisions_CreatorUserId" ON "EmailTemplateRevisions" ("CreatorUserId");

CREATE INDEX "IX_EmailTemplateRevisions_EmailTemplateId" ON "EmailTemplateRevisions" ("EmailTemplateId");

CREATE INDEX "IX_EmailTemplateRevisions_LastModifierUserId" ON "EmailTemplateRevisions" ("LastModifierUserId");

CREATE INDEX "IX_EmailTemplates_CreatorUserId" ON "EmailTemplates" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_EmailTemplates_DeveloperName" ON "EmailTemplates" ("DeveloperName");

CREATE INDEX "IX_EmailTemplates_LastModifierUserId" ON "EmailTemplates" ("LastModifierUserId");

CREATE UNIQUE INDEX "IX_JwtLogins_Jti" ON "JwtLogins" ("Jti");

CREATE INDEX "IX_MediaItems_CreatorUserId" ON "MediaItems" ("CreatorUserId");

CREATE INDEX "IX_MediaItems_LastModifierUserId" ON "MediaItems" ("LastModifierUserId");

CREATE INDEX "IX_MediaItems_ObjectKey" ON "MediaItems" ("ObjectKey");

CREATE INDEX "IX_NavigationMenuItems_CreatorUserId" ON "NavigationMenuItems" ("CreatorUserId");

CREATE INDEX "IX_NavigationMenuItems_LastModifierUserId" ON "NavigationMenuItems" ("LastModifierUserId");

CREATE INDEX "IX_NavigationMenuItems_NavigationMenuId" ON "NavigationMenuItems" ("NavigationMenuId");

CREATE INDEX "IX_NavigationMenuItems_ParentNavigationMenuItemId" ON "NavigationMenuItems" ("ParentNavigationMenuItemId");

CREATE INDEX "IX_NavigationMenuRevisions_CreatorUserId" ON "NavigationMenuRevisions" ("CreatorUserId");

CREATE INDEX "IX_NavigationMenuRevisions_LastModifierUserId" ON "NavigationMenuRevisions" ("LastModifierUserId");

CREATE INDEX "IX_NavigationMenuRevisions_NavigationMenuId" ON "NavigationMenuRevisions" ("NavigationMenuId");

CREATE INDEX "IX_NavigationMenus_CreatorUserId" ON "NavigationMenus" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_NavigationMenus_DeveloperName" ON "NavigationMenus" ("DeveloperName");

CREATE INDEX "IX_NavigationMenus_LastModifierUserId" ON "NavigationMenus" ("LastModifierUserId");

CREATE INDEX "IX_OneTimePasswords_UserId" ON "OneTimePasswords" ("UserId");

CREATE INDEX "IX_RaythaFunctionRevisions_CreatorUserId" ON "RaythaFunctionRevisions" ("CreatorUserId");

CREATE INDEX "IX_RaythaFunctionRevisions_LastModifierUserId" ON "RaythaFunctionRevisions" ("LastModifierUserId");

CREATE INDEX "IX_RaythaFunctionRevisions_RaythaFunctionId" ON "RaythaFunctionRevisions" ("RaythaFunctionId");

CREATE INDEX "IX_RaythaFunctions_CreatorUserId" ON "RaythaFunctions" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_RaythaFunctions_DeveloperName" ON "RaythaFunctions" ("DeveloperName");

CREATE INDEX "IX_RaythaFunctions_LastModifierUserId" ON "RaythaFunctions" ("LastModifierUserId");

CREATE INDEX "IX_Roles_CreatorUserId" ON "Roles" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_Roles_DeveloperName" ON "Roles" ("DeveloperName");

CREATE INDEX "IX_Roles_LastModifierUserId" ON "Roles" ("LastModifierUserId");

CREATE INDEX "IX_RoleUser_UsersId" ON "RoleUser" ("UsersId");

CREATE UNIQUE INDEX "IX_Routes_Path" ON "Routes" ("Path");

CREATE INDEX "IX_ThemeAccessToMediaItems_MediaItemId" ON "ThemeAccessToMediaItems" ("MediaItemId");

CREATE INDEX "IX_ThemeAccessToMediaItems_ThemeId" ON "ThemeAccessToMediaItems" ("ThemeId");

CREATE INDEX "IX_Themes_CreatorUserId" ON "Themes" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_Themes_DeveloperName" ON "Themes" ("DeveloperName");

CREATE INDEX "IX_Themes_LastModifierUserId" ON "Themes" ("LastModifierUserId");

CREATE INDEX "IX_UserGroups_CreatorUserId" ON "UserGroups" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_UserGroups_DeveloperName" ON "UserGroups" ("DeveloperName");

CREATE INDEX "IX_UserGroups_LastModifierUserId" ON "UserGroups" ("LastModifierUserId");

CREATE INDEX "IX_Users_AuthenticationSchemeId" ON "Users" ("AuthenticationSchemeId");

CREATE INDEX "IX_Users_CreatorUserId" ON "Users" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_Users_EmailAddress" ON "Users" ("EmailAddress");

CREATE INDEX "IX_Users_LastModifierUserId" ON "Users" ("LastModifierUserId");

CREATE UNIQUE INDEX "IX_Users_SsoId_AuthenticationSchemeId" ON "Users" ("SsoId", "AuthenticationSchemeId");

CREATE INDEX "IX_UserUserGroup_UsersId" ON "UserUserGroup" ("UsersId");

CREATE INDEX "IX_UserView_UserFavoritesId" ON "UserView" ("UserFavoritesId");

CREATE INDEX "IX_VerificationCodes_CreatorUserId" ON "VerificationCodes" ("CreatorUserId");

CREATE INDEX "IX_VerificationCodes_LastModifierUserId" ON "VerificationCodes" ("LastModifierUserId");

CREATE INDEX "IX_Views_ContentTypeId" ON "Views" ("ContentTypeId");

CREATE INDEX "IX_Views_CreatorUserId" ON "Views" ("CreatorUserId");

CREATE INDEX "IX_Views_LastModifierUserId" ON "Views" ("LastModifierUserId");

CREATE UNIQUE INDEX "IX_Views_RouteId" ON "Views" ("RouteId");

CREATE INDEX "IX_WebTemplateAccessToModelDefinitions_ContentTypeId" ON "WebTemplateAccessToModelDefinitions" ("ContentTypeId");

CREATE INDEX "IX_WebTemplateAccessToModelDefinitions_WebTemplateId" ON "WebTemplateAccessToModelDefinitions" ("WebTemplateId");

CREATE INDEX "IX_WebTemplateContentItemRelations_ContentItemId" ON "WebTemplateContentItemRelations" ("ContentItemId");

CREATE UNIQUE INDEX "IX_WebTemplateContentItemRelations_WebTemplateId_ContentItemId" ON "WebTemplateContentItemRelations" ("WebTemplateId", "ContentItemId");

CREATE INDEX "IX_WebTemplateRevisions_CreatorUserId" ON "WebTemplateRevisions" ("CreatorUserId");

CREATE INDEX "IX_WebTemplateRevisions_EmailTemplateId" ON "WebTemplateRevisions" ("EmailTemplateId");

CREATE INDEX "IX_WebTemplateRevisions_LastModifierUserId" ON "WebTemplateRevisions" ("LastModifierUserId");

CREATE INDEX "IX_WebTemplateRevisions_WebTemplateId" ON "WebTemplateRevisions" ("WebTemplateId");

CREATE INDEX "IX_WebTemplates_CreatorUserId" ON "WebTemplates" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_WebTemplates_DeveloperName_ThemeId" ON "WebTemplates" ("DeveloperName", "ThemeId");

CREATE INDEX "IX_WebTemplates_LastModifierUserId" ON "WebTemplates" ("LastModifierUserId");

CREATE INDEX "IX_WebTemplates_ParentTemplateId" ON "WebTemplates" ("ParentTemplateId");

CREATE INDEX "IX_WebTemplates_ThemeId" ON "WebTemplates" ("ThemeId");

CREATE UNIQUE INDEX "IX_WebTemplateViewRelations_ViewId_WebTemplateId" ON "WebTemplateViewRelations" ("ViewId", "WebTemplateId");

CREATE INDEX "IX_WebTemplateViewRelations_WebTemplateId" ON "WebTemplateViewRelations" ("WebTemplateId");

ALTER TABLE "ApiKeys" ADD CONSTRAINT "FK_ApiKeys_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id");

ALTER TABLE "ApiKeys" ADD CONSTRAINT "FK_ApiKeys_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

ALTER TABLE "AuthenticationSchemes" ADD CONSTRAINT "FK_AuthenticationSchemes_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id");

ALTER TABLE "AuthenticationSchemes" ADD CONSTRAINT "FK_AuthenticationSchemes_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id");

INSERT INTO "Themes" ("Id", "Title", "DeveloperName", "IsExportable", "Description", "CreationTime")
VALUES ('e31cb739-c764-4423-9f45-9dc6f3365766', 'Raytha default theme', 'raytha_default_theme', FALSE, 'Raytha default theme', TIMESTAMPTZ '2025-11-29T15:29:46.627125Z');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241110181505_v1_4_0', '10.0.0');

COMMIT;

START TRANSACTION;

                UPDATE "ContentTypeFields"
                SET "FieldType" = 'wysiwyg'
                WHERE "FieldType" = 'long_text';
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241213092139_v1_4_1', '10.0.0');

COMMIT;

START TRANSACTION;
ALTER TABLE "Routes" ADD "SitePageId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "AuthenticationSchemes" ADD "BruteForceProtectionMaxFailedAttempts" integer NOT NULL DEFAULT 0;

ALTER TABLE "AuthenticationSchemes" ADD "BruteForceProtectionWindowInSeconds" integer NOT NULL DEFAULT 0;

CREATE TABLE "FailedLoginAttempts" (
    "Id" uuid NOT NULL,
    "EmailAddress" text NOT NULL,
    "FailedAttemptCount" integer NOT NULL,
    "LastFailedAttemptAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FailedLoginAttempts" PRIMARY KEY ("Id")
);

CREATE TABLE "SitePages" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "IsPublished" boolean NOT NULL,
    "IsDraft" boolean NOT NULL,
    "RouteId" uuid NOT NULL,
    "WebTemplateId" uuid NOT NULL,
    "_DraftWidgetsJson" jsonb,
    "_PublishedWidgetsJson" jsonb,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_SitePages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SitePages_Routes_RouteId" FOREIGN KEY ("RouteId") REFERENCES "Routes" ("Id"),
    CONSTRAINT "FK_SitePages_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_SitePages_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_SitePages_WebTemplates_WebTemplateId" FOREIGN KEY ("WebTemplateId") REFERENCES "WebTemplates" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WidgetTemplates" (
    "Id" uuid NOT NULL,
    "ThemeId" uuid NOT NULL,
    "Label" text,
    "DeveloperName" text,
    "Content" text,
    "IsBuiltInTemplate" boolean NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_WidgetTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WidgetTemplates_Themes_ThemeId" FOREIGN KEY ("ThemeId") REFERENCES "Themes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WidgetTemplates_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WidgetTemplates_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "SitePageRevisions" (
    "Id" uuid NOT NULL,
    "_PublishedWidgetsJson" jsonb,
    "SitePageId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_SitePageRevisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SitePageRevisions_SitePages_SitePageId" FOREIGN KEY ("SitePageId") REFERENCES "SitePages" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SitePageRevisions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_SitePageRevisions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "WidgetTemplateRevisions" (
    "Id" uuid NOT NULL,
    "Label" text,
    "Content" text,
    "WidgetTemplateId" uuid NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "CreatorUserId" uuid,
    "LastModifierUserId" uuid,
    CONSTRAINT "PK_WidgetTemplateRevisions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WidgetTemplateRevisions_Users_CreatorUserId" FOREIGN KEY ("CreatorUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WidgetTemplateRevisions_Users_LastModifierUserId" FOREIGN KEY ("LastModifierUserId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_WidgetTemplateRevisions_WidgetTemplates_WidgetTemplateId" FOREIGN KEY ("WidgetTemplateId") REFERENCES "WidgetTemplates" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_FailedLoginAttempts_EmailAddress" ON "FailedLoginAttempts" ("EmailAddress");

CREATE INDEX "IX_SitePageRevisions_CreatorUserId" ON "SitePageRevisions" ("CreatorUserId");

CREATE INDEX "IX_SitePageRevisions_LastModifierUserId" ON "SitePageRevisions" ("LastModifierUserId");

CREATE INDEX "IX_SitePageRevisions_SitePageId" ON "SitePageRevisions" ("SitePageId");

CREATE INDEX "IX_SitePages_CreatorUserId" ON "SitePages" ("CreatorUserId");

CREATE INDEX "IX_SitePages_LastModifierUserId" ON "SitePages" ("LastModifierUserId");

CREATE UNIQUE INDEX "IX_SitePages_RouteId" ON "SitePages" ("RouteId");

CREATE INDEX "IX_SitePages_WebTemplateId" ON "SitePages" ("WebTemplateId");

CREATE INDEX "IX_WidgetTemplateRevisions_CreatorUserId" ON "WidgetTemplateRevisions" ("CreatorUserId");

CREATE INDEX "IX_WidgetTemplateRevisions_LastModifierUserId" ON "WidgetTemplateRevisions" ("LastModifierUserId");

CREATE INDEX "IX_WidgetTemplateRevisions_WidgetTemplateId" ON "WidgetTemplateRevisions" ("WidgetTemplateId");

CREATE INDEX "IX_WidgetTemplates_CreatorUserId" ON "WidgetTemplates" ("CreatorUserId");

CREATE UNIQUE INDEX "IX_WidgetTemplates_DeveloperName_ThemeId" ON "WidgetTemplates" ("DeveloperName", "ThemeId");

CREATE INDEX "IX_WidgetTemplates_LastModifierUserId" ON "WidgetTemplates" ("LastModifierUserId");

CREATE INDEX "IX_WidgetTemplates_ThemeId" ON "WidgetTemplates" ("ThemeId");


                UPDATE "Roles"
                SET "SystemPermissions" = "SystemPermissions" | 64
                WHERE "DeveloperName" IN ('super_admin', 'admin', 'editor');
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251129000211_v1_5_0', '10.0.0');

COMMIT;

