<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Raytha.Infrastructure</RootNamespace>
    <AssemblyName>Raytha.Infrastructure</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Debug without JS</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Raytha.Infrastructure.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Raytha.Application\Raytha.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Npgsql" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Dapper.SqlBuilder" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.ClearScript.V8" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.linux-x64" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.OData.Core" />
    <PackageReference Include="Microsoft.AspNetCore.OData" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
